version: "3.7"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3355:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/